### PR TITLE
doc: Add Yi as a notary roadmap maintainer

### PR DESCRIPTION
**Pull request by FeynmanZhou**
Signed-off-by: Feynman Zhou <feynmanzhou@microsoft.com>

### CODE REVIEW

**Review by gokarnm — APPROVED** [review]
LGTM but IANAM

**Review by priteshbandi — APPROVED** [review]
LGTM but IANAM

**Comment by iamsamirzon** [comment]
LGTM but IANAM

**Comment by yizha1** [comment]
Close this issue as aggregated PR https://github.com/notaryproject/roadmap/pull/85 was merged.

**Pull request closed without merging**
