### PR TITLE
Add Vani Rao as a roadmap maintainer

### PR DESCRIPTION
**Pull request by vaninrao10**
Add Vani Rao as a seed maintainer of roadmap based on their activity and as per - https://github.com/notaryproject/roadmap/issues/78

Signed-off-by: vaninrao10 <111005862+vaninrao10@users.noreply.github.com>

### CODE REVIEW

**Review by toddysm — DISMISSED** [review]
LGTM but IANAM

**Review by yizha1 — DISMISSED** [review]
LGTM but IANAM

**Review by gokarnm — DISMISSED** [review]
LGTM but IANAM

**Review by priteshbandi — APPROVED** [review]
LGTM but IANAM

**Review by iamsamirzon — APPROVED** [review]

**Comment by yizha1** [comment]
Close this issue as aggregated PR https://github.com/notaryproject/roadmap/pull/85 was merged.

**Pull request closed without merging**
